- name: Copying required files
  template:
    src: nginx_container_restart.py
    dest: /tmp/

- name: Change file ownership, group and permissions
  file:
    path: "{{ python_script_path }}"
    mode: '0777'

- name: copy file from local host to remote host
  copy:
    src: my_123.py
    dest: /tmp/my_123.py

- name: Run a script using an executable in a system path
  shell: "{{ python_script_path }}"

#- name: Nginx restart
#   shell: "ls /etc/"
- name: "Check if my sites is accessible."
  uri:
    url: "{{ url_to_check }}"
    method: GET
    status_code: 200