- name: Copying required files
  template:
    src: nginx_container_restart.py
    dest: /tmp/

- name: Change file ownership, group and permissions
  file:
    path: /tmp/nginx_container_restart.py
    mode: '0777'

- name: copy file from local host to remote host
  copy:
    src: my_123.py
    dest: /tmp/my_123.py

- name: Run a script using an executable in a system path
  shell: /tmp/nginx_container_restart.py

#- name: Nginx restart
#   shell: "ls /etc/"
- name: "Check if my sites is accessible."
  uri:
    url: https://blog.n3yron.ru
    method: GET
    status_code: 200